#!/bin/bash
#
# NurCake POS Sync Server - Setup Script
# 
# Script ini menginstall dan mengkonfigurasi NurCake POS sync server
# pada STB Armbian.
#
# PENGGUNAAN:
# chmod +x setup.sh
# sudo ./setup.sh
#

set -e

# ============================================================================
# CONFIGURATION
# ============================================================================

INSTALL_DIR="/opt/nurcake-sync"
DB_NAME="nurcake_pos"
DB_USER="izanm"
BACKUP_DIR="/var/backups/nurcake"
LOG_DIR="/var/log/nurcake"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

print_header() {
    echo ""
    echo "========================================"
    echo -e "${GREEN}$1${NC}"
    echo "========================================"
    echo ""
}

print_step() {
    echo -e "${YELLOW}→ $1${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

check_root() {
    if [ "$EUID" -ne 0 ]; then
        print_error "Script ini harus dijalankan sebagai root"
        echo "Gunakan: sudo ./setup.sh"
        exit 1
    fi
}

# ============================================================================
# INSTALLATION STEPS
# ============================================================================

install_dependencies() {
    print_header "Installing Dependencies"
    
    print_step "Updating package list..."
    apt-get update
    
    print_step "Installing PostgreSQL..."
    apt-get install -y postgresql postgresql-contrib
    
    print_step "Installing Node.js..."
    # Check if Node.js is already installed
    if command -v node &> /dev/null; then
        NODE_VERSION=$(node -v)
        echo "Node.js already installed: $NODE_VERSION"
    else
        # Install Node.js 18.x LTS
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        apt-get install -y nodejs
    fi
    
    print_step "Installing utilities..."
    apt-get install -y curl wget git unzip
    
    print_success "Dependencies installed"
}

setup_postgresql() {
    print_header "Setting Up PostgreSQL"
    
    # Start PostgreSQL if not running
    systemctl start postgresql
    systemctl enable postgresql
    
    print_step "Creating database user..."
    
    # Generate random password
    DB_PASSWORD=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 24)
    
    # Create user and database
    sudo -u postgres psql -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';" 2>/dev/null || true
    sudo -u postgres psql -c "CREATE DATABASE $DB_NAME OWNER $DB_USER;" 2>/dev/null || true
    sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;" 2>/dev/null || true
    
    # Save password to temp file for later
    echo "$DB_PASSWORD" > /tmp/nurcake_db_password.txt
    chmod 600 /tmp/nurcake_db_password.txt
    
    print_success "PostgreSQL configured"
    echo "Database: $DB_NAME"
    echo "User: $DB_USER"
    echo "Password saved to /tmp/nurcake_db_password.txt"
}

setup_directories() {
    print_header "Setting Up Directories"
    
    print_step "Creating installation directory..."
    mkdir -p "$INSTALL_DIR"
    
    print_step "Creating backup directory..."
    mkdir -p "$BACKUP_DIR"/{daily,hourly,sync,manual}
    
    print_step "Creating log directory..."
    mkdir -p "$LOG_DIR"
    
    # Create nurcake user if doesn't exist
    if ! id "nurcake" &>/dev/null; then
        print_step "Creating nurcake user..."
        useradd -r -s /bin/false nurcake
    fi
    
    # Set permissions
    chown -R nurcake:nurcake "$BACKUP_DIR"
    chown -R nurcake:nurcake "$LOG_DIR"
    
    print_success "Directories created"
}

copy_server_files() {
    print_header "Copying Server Files"
    
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    SERVER_DIR="$(dirname "$SCRIPT_DIR")"
    
    print_step "Copying server files to $INSTALL_DIR..."
    cp -r "$SERVER_DIR"/* "$INSTALL_DIR/"
    
    print_step "Setting permissions..."
    chown -R nurcake:nurcake "$INSTALL_DIR"
    chmod +x "$INSTALL_DIR/scripts/"*.sh
    
    print_success "Server files copied"
}

configure_environment() {
    print_header "Configuring Environment"
    
    DB_PASSWORD=$(cat /tmp/nurcake_db_password.txt)
    API_SECRET=$(openssl rand -base64 32)
    
    print_step "Creating .env file..."
    cat > "$INSTALL_DIR/server/.env" << EOF
# ============================================
# NurCake Sync Server Configuration
# Generated by setup.sh on $(date)
# ============================================

# Server
PORT=3000
NODE_ENV=production

# Database PostgreSQL
DB_HOST=localhost
DB_PORT=5432
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD

# Security
API_KEY_SECRET=$API_SECRET
CORS_ORIGIN=*

# Backup
BACKUP_DIR=$BACKUP_DIR
LOG_DIR=$LOG_DIR

# Logging
LOG_LEVEL=info
EOF

    chmod 600 "$INSTALL_DIR/server/.env"
    chown nurcake:nurcake "$INSTALL_DIR/server/.env"
    
    # Remove temp password file
    rm -f /tmp/nurcake_db_password.txt
    
    print_success "Environment configured"
}

install_node_packages() {
    print_header "Installing Node.js Packages"
    
    print_step "Installing npm packages..."
    cd "$INSTALL_DIR/server"
    npm install --production
    
    print_success "Node packages installed"
}

initialize_database() {
    print_header "Initializing Database"
    
    cd "$INSTALL_DIR/server"
    
    print_step "Running database initialization..."
    npm run db:init
    
    print_step "Seeding master data..."
    npm run db:seed
    
    print_success "Database initialized"
}

setup_systemd_service() {
    print_header "Setting Up Systemd Service"
    
    print_step "Copying service file..."
    cp "$INSTALL_DIR/server/nurcake-sync.service" /etc/systemd/system/
    
    # Update paths in service file
    sed -i "s|/opt/nurcake-sync|$INSTALL_DIR|g" /etc/systemd/system/nurcake-sync.service
    
    print_step "Reloading systemd..."
    systemctl daemon-reload
    
    print_step "Enabling service..."
    systemctl enable nurcake-sync
    
    print_step "Starting service..."
    systemctl start nurcake-sync
    
    # Wait a moment and check status
    sleep 2
    if systemctl is-active --quiet nurcake-sync; then
        print_success "Service started successfully"
    else
        print_error "Service failed to start. Check logs with: journalctl -u nurcake-sync"
    fi
}

setup_cron_backup() {
    print_header "Setting Up Backup Cron Jobs"
    
    print_step "Creating backup cron jobs..."
    
    # Create cron file
    cat > /etc/cron.d/nurcake-backup << EOF
# NurCake POS Backup Jobs
# Daily backup at 2 AM
0 2 * * * nurcake $INSTALL_DIR/scripts/backup.sh daily >> $LOG_DIR/backup-cron.log 2>&1

# Hourly backup
0 * * * * nurcake $INSTALL_DIR/scripts/backup.sh hourly >> $LOG_DIR/backup-cron.log 2>&1

# Weekly cleanup on Sunday at 3 AM
0 3 * * 0 nurcake $INSTALL_DIR/scripts/backup.sh cleanup >> $LOG_DIR/backup-cron.log 2>&1
EOF
    
    chmod 644 /etc/cron.d/nurcake-backup
    
    print_success "Backup cron jobs configured"
}

setup_firewall() {
    print_header "Configuring Firewall"
    
    # Check if ufw is installed
    if command -v ufw &> /dev/null; then
        print_step "Allowing port 3000 through firewall..."
        ufw allow 3000/tcp
        print_success "Firewall configured"
    else
        echo "UFW not installed, skipping firewall configuration"
        echo "Make sure port 3000 is accessible from your local network"
    fi
}

print_summary() {
    print_header "Setup Complete!"
    
    # Get server IP
    SERVER_IP=$(hostname -I | awk '{print $1}')
    
    echo "NurCake POS Sync Server telah berhasil diinstall!"
    echo ""
    echo "========================================"
    echo "  INFORMASI SERVER"
    echo "========================================"
    echo ""
    echo "  Server URL:    http://$SERVER_IP:3000"
    echo "  API Endpoint:  http://$SERVER_IP:3000/api/v1"
    echo "  Health Check:  http://$SERVER_IP:3000/api/v1/health"
    echo ""
    echo "========================================"
    echo "  DIREKTORI"
    echo "========================================"
    echo ""
    echo "  Instalasi:     $INSTALL_DIR"
    echo "  Backup:        $BACKUP_DIR"
    echo "  Log:           $LOG_DIR"
    echo ""
    echo "========================================"
    echo "  PERINTAH BERGUNA"
    echo "========================================"
    echo ""
    echo "  Status server:   sudo systemctl status nurcake-sync"
    echo "  Lihat logs:      sudo journalctl -u nurcake-sync -f"
    echo "  Restart server:  sudo systemctl restart nurcake-sync"
    echo "  Manual backup:   $INSTALL_DIR/scripts/backup.sh manual"
    echo "  Backup status:   $INSTALL_DIR/scripts/backup.sh status"
    echo ""
    echo "========================================"
    echo "  LANGKAH SELANJUTNYA"
    echo "========================================"
    echo ""
    echo "  1. Update SYNC_CONFIG.SERVER_URL di React Native app:"
    echo "     SERVER_URL = 'http://$SERVER_IP:3000/api/v1'"
    echo ""
    echo "  2. Test koneksi:"
    echo "     curl http://$SERVER_IP:3000/api/v1/health"
    echo ""
    echo "  3. Register device pertama melalui app"
    echo ""
    echo "========================================"
}

# ============================================================================
# MAIN
# ============================================================================

main() {
    print_header "NurCake POS Sync Server Setup"
    echo "Script ini akan menginstall dan mengkonfigurasi"
    echo "sync server untuk NurCake POS pada STB Armbian."
    echo ""
    
    read -p "Lanjutkan instalasi? (y/n): " confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "Instalasi dibatalkan."
        exit 0
    fi
    
    check_root
    install_dependencies
    setup_postgresql
    setup_directories
    copy_server_files
    configure_environment
    install_node_packages
    initialize_database
    setup_systemd_service
    setup_cron_backup
    setup_firewall
    print_summary
}

# Run main function
main "$@"
